AutoModo-App/app/dealership/api/urls.py
from rest_framework.routers import DefaultRouter, path
from api.views.cars_views import CarViewSet
from api.views.register_views import UserRegisterViewSet
from api.views.offer_views import OfferReadOnlyViewSet
from api.views.comments_view import CommmentViewSet
from api.views.comments_by_car_view import CarModelOffersListView

router = DefaultRouter()
router.register(r'cars', CarViewSet,'cars')
router.register(r'register', UserRegisterViewSet, 'register')
router.register(r'offers', OfferReadOnlyViewSet)
router.register(r'comments', CommmentViewSet,'comments')

urlpatterns = [
 path('commentsByCar/<int:car_model_id>/', CarModelOffersListView.as_view(), name='commentsByCar'), 
]

urlpatterns += router.urls

AutoModo-App/app/dealership/dealership/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import (
    path, 
    include
    )
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.authentication import BasicAuthentication

schema_view = get_schema_view(
   openapi.Info(
      title="Documentacion Dealership API",
      default_version='v1',
      description="Documentacion para EFI",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
   authentication_classes=[BasicAuthentication],
)


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
    path('locations/', include('locations.urls')),
    path('payment/', include('payments.urls')),
    path('offers/', include('offer.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AutoModo-App/app/dealership/home/urls.py
from django.urls import path

from home.views import (
        LoginView,
        LogoutView,
        IndexView,
        RegisterView,
    )


urlpatterns = [
    path(route = '', view = IndexView.as_view(), name = 'index'),
    path(route = 'register/', view = RegisterView.as_view(), name = 'register'),
    path(route = 'login/', view = LoginView.as_view(), name = 'login'),
    path(route = 'logout/', view = LogoutView.as_view(), name = 'logout')
]

AutoModo-App/app/dealership/cars/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Brand(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('brand'))
    def __str__(self):
        return  self.name
    
class CarModel(models.Model):
    name = models.CharField(max_length=200,verbose_name=_('model'))
    brand = models.ForeignKey(
        Brand,
        on_delete = models.CASCADE, 
        related_name = 'brands', #related name en plural
        null=False
    )
    def __str__(self):
        return  self.name

class Category(models.Model):
    name = models.CharField(max_length=200,verbose_name=_('category'))
    def __str__(self):
        return  self.name
    
class Car(models.Model):
    car_model = models.ForeignKey(
        CarModel,
        on_delete = models.CASCADE, 
        related_name = 'car_models',
        null=False
    )
    category = models.ForeignKey(
        Category,
        on_delete = models.CASCADE, 
        related_name = 'categories',
        null=False
    )
    def __str__(self):
        return  f"{self.car_model.brand.name} {self.car_model.name} - {self.category.name} "
    

AutoModo-App/app/dealership/api/views/register_views.py
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated,  IsAdminUser
from django.contrib.auth.models import User
from api.serializers.profile_serializer import UserRegisterSerializer
# from rest_framework.permissions import IsAdminUser
from rest_framework.decorators import api_view, permission_classes


class UserRegisterViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserRegisterSerializer
    # permission_classes = [IsAdminUser]
    
    def get_permissions(self):
        if self.action == 'create':
            self.permission_classes = [IsAuthenticated] 
        else:
            self.permission_classes = [AllowAny]  
        return super().get_permissions()


    def create(self, request, *args, **kwargs):
        """
        Creacion de usuario por parte de usuario staff

        Requisito = pasar usuario y contraseña de usuario staff
        """
        # El get se encarga de buscar el serialezer_class
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        headers = self.get_success_headers(serializer.data)
        
        response_data = {
            "message": "Usuario registrado exitosamente",
            "user": UserRegisterSerializer(user).data
        }
        
        return Response(
            response_data, 
            status=status.HTTP_201_CREATED, 
            headers=headers
        )

AutoModo-App/app/dealership/home/views.py
from django.contrib.auth import (
        authenticate, 
        login, 
        logout
    )

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views import (
    View,

)

from users.forms import UserRegisterForm

class LoginView(View):
    def get(self, request): # Renderiza el formulario.
        return render(
            request, 
            'home/login.html'
        
        )
    
    def post(self, request): # Información que envía el usuario.
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(
                request,
                username = username,
                password = password

            )

            if user:
                login(request, user) # Hacemos uso de la función que importamos más arriba

                return redirect('index')
        
        return redirect('login')

class LogoutView(View):
    def get(self, request):
        logout(request)
        
        return redirect('login')
    
# Create your views here.

class RegisterView(View):
    form_class = UserRegisterForm
    template_name = 'home/register.html'

    def get(self, request):
        form = self.form_class()
        
        return render(
            request,
            self.template_name,
            dict(
                form = form
            
            )
        
        )

    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            
            return redirect("register")
        
        return render(
            request,
            self.template_name,
            dict(
                form=form
            )
        )

class IndexView(View):
    def get(self, request):
        if request.user.is_authenticated:
            data_current_user = {
                'is_authenticated': True,
                'username': request.user.username,
                'is_staff': request.user.is_staff,
                'email': request.user.email,
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'is_seller': request.user.profile.is_seller

            }
        
        else:
            data_current_user = {
                'is_authenticated': False,
                'username': 'Invitado',
                'is_staff': False,
                'email': None,
                'first_name': '',
                'last_name': '',
            
            }
        
        return render(
            request,    
            'home/index.html',
            dict(
                current_user = data_current_user
                
            )
        
        )

AutoModo-App/app/dealership/home/templates/home/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
  <link rel="icon" href="{% static 'home/images/favicon.ico' %}">
  {% block extra_css %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid p-3">
      <div class="d-block">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img class="img-brand" src="{% static 'home/images/Logo.svg' %}" alt="">
        </a>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'index' %}">{% trans "Inicio" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'listOffers' %}">{% trans "Nuestras Ofertas" %}</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="dropdownMenuButton" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              {% trans "Categorías" %}
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for name in names_categories %}
              <li><a class="dropdown-item text-dark" href="#">{{name}}</a></li>
              {% endfor %}
            </ul>
          </li>
          <button class="btn p-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#Id1" aria-controls="Id1">
            <img class="hamburguer-logo mx-2" src="{% static 'home/images/list.svg' %}">
          </button>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="dropdownProfileButton" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% static 'home/images/person-lines-fill.svg' %}" alt="">
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownProfileButton">
              {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="dropdown-item text-decoration-none text-dark">
                {% trans "Cerrar Sesión" %}</a>
              {% else %}
              <a href="{% url 'login' %}" class="dropdown-item text-decoration-none text-dark">{% trans "Ingresá" %}</a>
              <hr class="dropdown-divider">
              <a href="{% url 'register' %}" class="dropdown-item text-decoration-none text-dark">
                {% trans "Registrate" %}</a>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="Id1"
    aria-labelledby="Enable both scrolling & backdrop">
    <div class="offcanvas-header">
      <h6 class="offcanvas-title" id="Enable both scrolling & backdrop">
        {% if user.is_authenticated %}
        {% trans "¡Hola," %} <b>{{username}}!</b>
        <br>
        <i>{% trans "Bienvenido a AutoMundo" %}</i>
        {% else %}
        <i>{% trans "Bienvenido a AutoMundo" %}</i>
        {% endif %}
      </h6>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      {% if user.is_authenticated %}
      {% if user.is_staff %}
      <div>
        <h6 class="mb-4"><b>{% trans "Ubicaciones" %}</b></h6>
        <a href="{% url 'countries_list' %}" class="link p-2 text-decoration-none text-dark">
          {% trans "Administrar Ubicaciones" %}</a>
        <hr>
      </div>
      <div>
        <h6 class="mt-4 mb-4"><b>{% trans "Vehículos" %}</b></h6>
        <a href="{% url 'car_list' %}" class="link p-2 text-decoration-none text-dark">
          {% trans "Administrar Vehículos" %}
        </a>
        <hr>
      </div>
      <div>
        <h6 class="mt-4 mb-4"><b>{% trans "Métodos de Pago" %}</b></h6>
        <a href="{% url 'payments_list' %}" class="link p-2 text-decoration-none text-dark">
          {% trans "Administrar Métodos de Pago" %}</a>
        <hr>
      </div>
      <div>
        <h6 class="mt-4 mb-4"><b>{% trans "Ofertas" %}</b></h6>
        <a href="{% url 'listOffers' %}" class="link p-2 text-decoration-none text-dark">
          {% trans "Administrar Ofertas" %}</a>
        <hr>
      </div>
      {% elif not user.is_staff %}
      <div>
        <a href="{% url 'index' %}" class="link p-2 text-decoration-none text-dark">{% trans "Inicio" %}</a>
        <hr>
        <a href="{% url 'listOffers' %}" class="link p-2 text-decoration-none text-dark">{% trans "Ofertas" %}</a>
        <hr>
        <a href="{% url 'logout' %}" class="link p-2 text-decoration-none text-danger">{% trans "Cerrar Sesión" %}</a>
      </div>
      {% endif %}
      {% else %}
      <p class="p-2 text-decoration-none text-dark">{% trans "Nosotros" %}</p>
      <hr>
      <a href="{% url 'listOffers' %}" class="p-2 text-decoration-none text-dark">{% trans "Ofertas" %}</a>
      {% endif %}
    </div>
  </div>

  <div class="container mt-4">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>
</body>

</html>

AutoModo-App/app/dealership/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Sitio Oficial: Inicio" %}| AutoModo Argentina{% endblock %}

{% block content %}
<div id="carouselId" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block w-100 carousel-img" src="{% static 'home/images/index/car-dealership.jpg' %}"
        alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carousel-img"
        src="{% static 'home/images/index/headlights-hood-black-luxury-car.jpg' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 carousel-img"
        src="{% static 'home/images/index/sport-car-with-black-white-autotuning-driving-forest.jpg' %}"
        alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselId" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
  <a class="carousel-control-next" href="#carouselId" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only"></span>
  </a>
</div>

<section class="">
  <div class="container-section-links container d-flex justify-content-center align-items-center mb-5">
    <!-- Primer div -->
    <a class="links d-flex flex-column align-items-center text-decoration-none text-dark" {% if user.is_authenticated %}
      href="{% url 'createOffers' %}" {% else %} href="{% url 'login' %}" {% endif %}>
      <div class="d-flex justify-content-center align-items-center bg-dark rounded-circle"
        style="height: 100px; width: 100px;">
        <img class="img-fluid img-section-links p-1" src="{% static 'home/images/index/laptop.svg' %}" alt="">
      </div>
      <p class="links text-center mt-2"><b><i>{% trans "Vendé" %}</i></b></p>
    </a>

    <!-- Segundo div -->
    <a class="d-flex flex-column align-items-center text-dark text-decoration-none" {% if user.is_authenticated %}
      id="modal-my-profile" href="{% url 'countries_list' %}" onclick="showMyProfile(event)" {% else %}
      href="{% url 'register' %}" {% endif %}>
      <div class="d-flex justify-content-center align-items-center bg-dark rounded-circle"
        style="height: 100px; width: 100px;">
        <img class="img-fluid img-section-links p-1" src="{% static 'home/images/index/person-circle.svg' %}" alt="">
      </div>
      {% if user.is_authenticated %}
      <p class="links text-center mt-2"><b><i>{% trans "Mi Perfil" %}</i></b></p>
      {% else %}
      <p class="links text-center mt-2"><b><i>{% trans "Registrarme" %}</i></b></p>
      {% endif %}
    </a>

    <!-- Tercer div -->
    <a class="links d-flex flex-column align-items-center text-decoration-none text-dark" href="">
      <div class="d-flex justify-content-center align-items-center bg-dark rounded-circle"
        style="height: 100px; width: 100px;">
        <img class="img-fluid img-section-links p-1" src="{% static 'home/images/index/person-raised-hand.svg' %}"
          alt="">
      </div>
      <p class="links text-center mt-2"><b><i>{% trans "Nosotros" %}</i></b></p>
    </a>

    <!-- Cuarto div -->
    <a class="links d-flex flex-column align-items-center text-decoration-none text-dark" href="{% url 'listOffers' %}">
      <div class="d-flex justify-content-center align-items-center bg-dark rounded-circle"
        style="height: 100px; width: 100px;">
        <img class="img-fluid img-section-links p-1" src="{% static 'home/images/index/bag.svg' %}" alt="">
      </div>
      <p class="links text-center mt-2"><b><i>{% trans "Comprá" %}</i></b></p>
    </a>
  </div>
</section>

<div class="container"></div>

<section class="container-fluid p-0 mb-5">
  <div class="row no-gutters">
    <div class="col-md-8">
      <div role="region" aria-label="Mapa de ubicación" class="w-100 h-100">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3342.3102580401046!2d-64.37070632352058!3d-33.10092627352996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95d20100455ae713%3A0x45c09be96f337c9!2sITEC%20R%C3%ADo%20Cuarto!5e0!3m2!1ses!2sar!4v1723313797200!5m2!1ses!2sar"
          width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
          referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
    <div class="col-md-4 d-flex justify-content-center align-items-center">
      <h4><b>{% trans "Dónde" %}</b> {% trans "nos encontramos" %}</h4>
      <hr class="ms-3 my-3 w-75">
    </div>
  </div>
</section>

<section class="py-3">
  <div class="d-flex inline-flex gap-5">
    <div>
      <a class="social-link">
        <img src="{% static '/home/images/index/social/instagram.svg' %}" alt="">
      </a>
    </div>
    <div>
      <a class="social-link">
        <img src="{% static '/home/images/index/social/facebook.svg' %}" alt="">
      </a>
    </div>
    <div>
      <a class="social-link">
        <img src="{% static '/home/images/index/social/twitter-x.svg' %}" alt="">
      </a>
    </div>
    <div>
      <a class="social-link">
        <img src="{% static '/home/images/index/social/youtube.svg' %}" alt="">
      </a>
    </div>
    <div>
      <a class="social-link">
        <img src="{% static '/home/images/index/social/whatsapp.svg' %}" alt="">
      </a>
    </div>
  </div>
</section>

<script>
  const showMyProfile = async (event) => {
    try {
      event.preventDefault();

      let modalElement = document.createElement('div');
      let username = '{{ current_user.username }}';
      let email = '{{ current_user.email }}';
      let firstName = '{{ current_user.first_name }}';
      let lastName = '{{ current_user.last_name }}';
      let isStaff = '{{ current_user.is_staff }}' === 'True' ? 'Staff' : 'No Staff';
      let isSeller = '{{ current_user.is_seller }}' === 'True' ? 'Vendedor' : 'Comprador';

      modalElement.className = 'modal fade';
      modalElement.tabIndex = -1;
      modalElement.id = 'modal-profile'

      let modalBodyContent = `<div class="modal-body">`;

      modalBodyContent += `
          <div class="mx-0 card h-25 row w-80 mt-3 mb-3">
              <p class="ps-4 mt-3 text-left"><b>Nombre de usuario</b></p>
              <hr class="w-100">
              <div class="d-flex w-100">
                  <p class='ms-3'><i>${username}</i></p>
              </div>
          </div>
          <hr>
          <div class="mx-0 card h-25 row w-80 mt-3 mb-3">
              <p class="ps-4 mt-3 text-left"><b>Correo electrónico</b></p>
              <hr class="w-100">
              <div class="d-flex w-100">
                  <p class='ms-3'><i>${email}</i></p>
              </div>
          </div>
          <hr>
          <div class="mx-0 card h-25 row w-80 mt-3 mb-3">
              <p class="ps-4 mt-3 text-left"><b>Nombre personal</b></p>
              <hr class="w-100">
              <div class="d-flex w-100">
                  <p class='ms-3'><i>${firstName}</i></p>
              </div>
          </div>
          <hr>
          <div class="mx-0 card h-25 row w-80 mt-3 mb-3">
              <p class="ps-4 mt-3 text-left"><b>Apellido</b></p>
              <hr class="w-100">
              <div class="d-flex w-100">
                  <p class='ms-3'><i>${lastName}</i></p>
              </div>
          </div>
          <div class="mx-0 card h-25 row w-80 mt-3 mb-3">
              <p class="ps-4 mt-3 text-left"><b>Tipo de usuario</b></p>
              <hr class="w-100">
              <div class="d-flex w-100">
                  <p class='ms-3'><i>${isStaff} | ${isSeller}</i></p>
              </div>
          </div>
          
        `;

      modalBodyContent += `</div>`;

      modalElement.innerHTML = `
          <div class="modal-dialog modal-profile-index d-flex justify-content-center align-items-center">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Mi Perfil</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </button>
              </div>
              ${modalBodyContent}
            </div>
          </div>
                    
        `;

      document.body.appendChild(modalElement);

      const myModal = new bootstrap.Modal(modalElement);
      myModal.show();

    } catch (error) {
      console.error(error);

    }

  };

</script>
{% endblock %}

AutoModo-App/app/dealership/home/templates/home/login.html
{% extends 'home/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Regístrate" %}| AutoModo {% endblock %}

{% block content %}
<div class="container mb-5 d-flex justify-content-center align-items-center" style="margin-left: 95px;">
  <div class="row align-items-stretch w-75">
    <div class="col-md-3 m-0 p-0 bg-white d-flex align-items-center justify-content-center shadow">
      <img src="{% static 'home/images/person-vcard.svg' %}" alt="" class="img-form">
    </div>
    <div class="col-md-9 m-0 p-0">
      <div class="container-form text-center shadow p-5" style="height: 500px;">
        <div class="d-flex justify-content-center align-items-center">
          <h2 class="text-start"><b>{% trans "Ingresá" %}</b><br>{% trans "tus datos" %}</h2>
          <hr class="w-100">
        </div>
        <form method="POST" action="{% url 'login' %}">
          {% csrf_token %}
          <div class="form-group">
            <input type="text" class="form-control mb-3" id="username" name="username" placeholder="Usuario">
            <input type="password" class="form-control mb-3" id="password" name="password" placeholder="Contraseña">
          </div>
          <div class="container-login-btn d-flex justify-content-center aling-items-center">
            <button type="submit" class="btn btn-outline-dark w-50 mb-3">{% trans "Ingresar" %}</button>
            <a href="{% url 'register' %}" class="text-decoration-none mb-2 ms-4 text-left text-dark register-title">
              {% trans "¿No tenés una cuenta?" %} <b>{% trans "Registrate gratis" %}</b></a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

AutoModo-App/app/dealership/home/templates/home/register.html
{% extends 'home/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Regístrate" %} | AutoModo {% endblock %}

{% block content %}
<div class="mt-5 mb-5 d-flex justify-content-center align-items-center" style="margin-left: 95px;">
  <div class="row align-items-stretch w-75">
    <div class="col-md-3 m-0 p-0 bg-white d-flex align-items-center justify-content-center shadow">
      <img src="{% static 'home/images/plugin.svg' %}" alt="" class="img-form">
    </div>
    <div class="col-md-9 m-0 p-0">
      <div class="container-form shadow p-5">
        <div class="d-flex justify-content-center align-items-center mt-4">
          <h2 class="text-start"><b>{% trans "Conectate" %}</b><br>{% trans "con nosotros" %}</h2>
          <hr class="w-100">
        </div>
        <form action="" method="POST">
          {% csrf_token %}
          <div class="input-group">
            {{ form.first_name }}
            {{ form.last_name }}
          </div>
          <div class="input-group">
            {{ form.username }}
            {% if form.username.errors %}
            <p class="text-danger">{{ form.username.errors }}</p>
            {% endif %}
          </div>
          <div class="input-group">
            {{ form.email }}
            {% if form.email.errors %}
            <p class="text-danger">{{ form.email.errors }}</p>
            {% endif %}
          </div>
          <div class="input-group">
            {{ form.password1 }}
            {% if form.password1.errors %}
            <p class="text-danger">{{ form.password1.errors }}</p>
            {% endif %}

            {{ form.password2 }}
            {% if form.password2.errors %}
            <p class="text-danger">{{ form.password2.errors }}</p>
            {% endif %}
          </div>
          <div class="input-group d-flex justify-content-center align-items-center mt-5">
            <div class="me-2">
              {{ form.is_seller.label_tag }}
            </div>
            <div>
              {{ form.is_seller }}
            </div>

            {% if form.is_seller.errors %}
            <p class="text-danger">{{form.is_seller.errors}}</p>
            {% endif %}
          </div>
          <div class="ms-4 d-flex justify-content-center align-items-center container-register-btn">
            <button type="submit" class="btn btn-outline-primary mt-3 w-50">{% trans "Registrarme" %}</button>
            <a class="text-decoration-none ms-4 text-center text-dark title login-title mt-3"
              href="{% url 'login' %}">{% trans "¿Ya tenés cuenta?" %} <b>{% trans "Iniciá sesión" %}</b></a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}